# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile.dev
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     environment:
#       - VITE_HOST=0.0.0.0
#       - VITE_BACKEND_URL=http://localhost:8080
#     networks:
#       - app-network

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_PROFILES_ACTIVE=dev
#       - DATASOURCE_URL=jdbc:postgresql://35.223.83.33:5432/AmsProject
#       - DATASOURCE_USERNAME=postgres
#       - DATASOURCE_PASSWORD=@rem$Adrian123
#       - FRONTEND_URL=http://localhost:3000
#     depends_on:
#       - db
#     networks:
#       - app-network

#   db:
#     image: postgres:14-alpine
#     environment:
#       - POSTGRES_DB=AmsProject
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=@rem$Adrian123
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - app-network

# volumes:
#   postgres_data:

# networks:
#   app-network:
#     driver: bridge