
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: AmsProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ams-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_DB=AmsProject
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATASOURCE_URL=jdbc:postgresql://db:5432/AmsProject
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - ams-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - ams-network

volumes:
  db-data:

networks:
  ams-network:
    driver: bridge
