version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ams-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - ams-network

networks:
  ams-network:
    driver: bridge
